version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: tesis_postgres
    restart: always
    environment:
      POSTGRES_DB: tesis_seg
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
